version: '3.4'
services:
  # override the one in birdhouse-deploy
  # assume this repo is checkout along-side repo "birdhouse-deploy"
  raven:
    volumes:
    - ../../birdhouse-deploy-ouranos/ouranos-config/raven/wps.cfg:/wps.cfg:ro

  proxy:
    volumes:
# This raven bypass Twitcher is for debugging only, should not be enabled
# permanently in prod.  Keep here as sample code and documentation how it can
# be done.
#    - ../../birdhouse-deploy-ouranos/ouranos-config/proxy/public-raven-bypass-twitcher.conf:/etc/nginx/conf.extra-service.d/raven/public-raven-bypass-twitcher.conf:ro
    - ../../birdhouse-deploy-ouranos/ouranos-config/proxy/cruesdeca-redirect.conf:/etc/nginx/conf.extra-service.d/redirect/cruesdeca-redirect.conf:ro
    - ${DATA_PERSIST_ROOT}/homepage:${DATA_PERSIST_ROOT}/homepage:ro
    - ../../birdhouse-deploy-ouranos/ouranos-config/proxy/catalog.conf:/etc/nginx/conf.extra-service.d/catalog/catalog.conf:ro
    - ${DATA_PERSIST_ROOT}/catalog:${DATA_PERSIST_ROOT}/catalog:ro
