version: '2.1'
services:
  generic_bird:
    volumes:
    # override the one in birdhouse-deploy
    # assume this repo is checkout along-side repo "birdhouse-deploy"
    - ../../birdhouse-deploy-ouranos/ouranos-config/generic_bird/wps.cfg:/wps.cfg:ro
  raven:
    volumes:
    - ../../birdhouse-deploy-ouranos/ouranos-config/raven/wps.cfg:/wps.cfg:ro

  proxy:
    volumes:
# This raven bypass Twitcher is for debugging only, should not be enabled
# permanently in prod.  Keep here as sample code and documentation how it can
# be done.
#    - ../../birdhouse-deploy-ouranos/ouranos-config/proxy/public-raven-bypass-twitcher.conf:/etc/nginx/conf.extra-service.d/raven/public-raven-bypass-twitcher.conf:ro
     - ../../birdhouse-deploy-ouranos/ouranos-config/proxy/increase-proxy_read_timeout.conf:/etc/nginx/conf.extra.d/proxy/increase-proxy_read_timeout.conf:ro
