version: '3.4'

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "50m"
    max-file: "10"

services:
  proxy:
    volumes:
# This raven bypass Twitcher is for debugging only, should not be enabled
# permanently in prod.  Keep here as sample code and documentation how it can
# be done.
#    - ../../birdhouse-deploy-ouranos/ouranos-config/proxy/public-raven-bypass-twitcher.conf:/etc/nginx/conf.extra-service.d/raven/public-raven-bypass-twitcher.conf:ro
    - ../../birdhouse-deploy-ouranos/ouranos-config/proxy/cruesdeca-redirect.conf:/etc/nginx/conf.extra-service.d/redirect/cruesdeca-redirect.conf:ro
    - ${DATA_PERSIST_ROOT}/homepage:${DATA_PERSIST_ROOT}/homepage:ro
    - ../../birdhouse-deploy-ouranos/ouranos-config/proxy/catalog.conf:/etc/nginx/conf.extra-service.d/catalog/catalog.conf:ro
    - ${DATA_PERSIST_ROOT}/catalog:${DATA_PERSIST_ROOT}/catalog:ro
    - ../../birdhouse-deploy-ouranos/ouranos-config/proxy/ogc-geoserver.conf:/etc/nginx/conf.extra-service.d/ogc/ogc-geoserver.conf:ro

  ogc-geoserver:
    image: pavics/geoserver:2.22.2-kartoza-build20230226
    container_name: ogc-geoserver
    volumes:
        # TODO use data volume to enforce max size
      - ${DATA_PERSIST_ROOT}/ogc-geoserver:/opt/geoserver/data_dir
    # Need port for WebUI internal access since not working behind front proxy.
    ports:
      - "8110:8080"
    restart: always
    environment:
      - GEOSERVER_DATA_DIR=/opt/geoserver/data_dir
      - GEOWEBCACHE_CACHE_DIR=/opt/geoserver/data_dir/gwc
      - GEOSERVER_ADMIN_PASSWORD=${GEOSERVER_ADMIN_PASSWORD}
      - GEOSERVER_ADMIN_USER=admin
      - INITIAL_MEMORY=2G
      - MAXIMUM_MEMORY=4G
      - STABLE_EXTENSIONS=netcdf-out-plugin,netcdf-plugin
      - COMMUNITY_EXTENSIONS=ncwms-plugin,colormap-plugin
    logging: *default-logging
    healthcheck:
      test: curl --fail --silent http://localhost:8080/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
