#!/bin/sh -x
# This script to be called by pavics-compose.sh.
# CWD is same as pavics-compose.sh.

OGC_GEOSERVER_DATA_DIR="${DATA_PERSIST_ROOT}/ogc-geoserver"

if [ ! -f "$OGC_GEOSERVER_DATA_DIR/global.xml" ]; then
  echo "fix OGC GeoServer data dir permission on first run only, when data dir do not exist yet."
  # Similar to the Geoserver in the PAVICS stack.
  FIRST_RUN_ONLY=1 ./deployment/fix-geoserver-data-dir-perm "$OGC_GEOSERVER_DATA_DIR"
fi
