version: '3.4'
services:

  # All the panel_serve "plumbing" configs have to be outside of the repo
  # containing the notebooks so that frequent notebook updates do not trigger
  # endlessly entire platform re-deployment.

  proxy:
    volumes:
    - ../../birdhouse-deploy-ouranos/panel_serve/proxy/analogues_spatiaux.conf:/etc/nginx/conf.extra-service.d/analogues_spatiaux/analogues_spatiaux.conf:ro

  analogues_spatiaux:
    image: pavics/workflow-tests:220518
    container_name: analogues_spatiaux
    ports:
    # Bypass front proxy for debugging, only accessible inside VPN.
    - 5008:5008
    volumes:
    # *** This should pre-exist before `docker-compose up -d`. ***
    - /data/panel_serve/analogues_spatiaux:/notebook_dir/analogues_spatiaux:ro
    command: bash -c "panel serve --port=5008 --allow-websocket-origin=* --prefix=/analogues_spatiaux /notebook_dir/analogues_spatiaux/app.ipynb"
    restart: always
    # TODO limit cpu/ram
    # TODO mount jupyter public root dir read-only
